### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by mmajcica** [geeklearningio/gl-vsts-tasks-build-scripts#15]
Guys,

I would like to use your package for setting up my build/package process of VSTS extensions.
I was able, thanks to looking of your projects, to get things going. However, a bit more of the documentation would be nice.
Still, I have a question; How to build my tasks only for a single environment and get it outputted in the .BuildOutput folder? Is that possible?

Thanks

**Comment by mmajcica** [comment]
I got it, inside the configuration file:
`"TaskIds": { "folderNameContainingTheTask": "desiredGuid" }`
is necessary.
However, is there a call that will just build a single environment in the .BuildOutput folder without creating the package and without versioning?

Thanks

**Comment by sandorfr** [comment]
Hi,

Thanks for the feedback. Documentation is indeed very much needed. If you can provide a bit of details about where you struggled, what you liked etc... It could help me prioritize.

You can build for only one environment just drop the two other ones from configuration.json.

When it comes to versionning I assume you are referring to the version transform for semver ? If that's the case you can use the flag `--noversiontransform`, ex:
```bash
yarn package --version 0.1.0 --noversiontransform
```

**Comment by asiffermann** [comment]
Hi @mmajcica, did you manage to use our package with the help provided by @sandorfr?

**Comment by mmajcica** [comment]
I have tried but ended up writing my own scripts wired with NPM for the purpose. The package, although has many good ideas, turned out not being flexible enough for me.

**Comment by asiffermann** [comment]
Thank you for taking the time to let us know!
It's true that this package is strictly tied to our way to develop pipelines tasks extensions... which evolves also with time 😉 

Happy Azure DevOps developments to you!

**Comment by mmajcica** [comment]
yaw, it still gave me some good inspiration for my own scripts :)
