### ISSUE TITLE
js.map and ts files

### ISSUE THREAD

**Issue by mmajcica** [geeklearningio/gl-vsts-tasks-build-scripts#16]
Above mentioned files are copied also from our Tasks folders into the .BuildOutput folder. Those are not necessary to be packaged.
Can we filter those out somehow?

**Comment by sandorfr** [comment]
you can change your tsconfig file to not emit those ones
```json
{
    "compilerOptions": {
        "sourceMap": false,
        "declaration": false
    }
}
```

**Comment by asiffermann** [comment]
Hi @mmajcica, did the change in your tsconfig file fixed your issue?

**Comment by mmajcica** [comment]
It was a valid suggestion but I haven't tried. However we can close this issue.
