### ISSUE TITLE
task names with azure devops pipelines

### ISSUE THREAD

**Issue by Plork** [geeklearningio/gl-vsts-tasks-build-scripts#21]
We use the build script for our extension development. But one thing I am not getting how to get  working.

We basically have the same setup with preview packages and release packages.

After the preview package we want to do some "system tests" actually validating that the task does its thing.

We configure this in yaml as a stage in azure devops. However the task name in preview and release stays the same.

preview
```
- task: AzureOnboarding@0
 inputs:
   ConfigureAzureDevops: false
```

release
```
- task: AzureOnboarding@0
 inputs:
   ConfigureAzureDevops: false
```

The display name in the azure devops portal does get the `DisplayNamesSuffix`

So how can i select which task to use when using the yml pipelines.

**Comment by Plork** [comment]
hmm found out I can prefix it with the extension name instead of only using the task name so then this wouldn't be needed anymore.

**Comment by sandorfr** [comment]
Sorry I did not find the time earlier, but yes we've done that with the `VssExtensionIdSuffix` in `configuration.json`. (We also use it to avoid custom endpoint collisions too)
