### ISSUE TITLE
Task Versionning and Preview Task support

### ISSUE THREAD

**Issue by sandorfr** [geeklearningio/gl-vsts-tasks-build-scripts#4]
We the new support of task version in vsts build, we now have the ability to push a preview version of a task as long as we update the major version number. 

We need to design how we could make it easy with our tooling.

**Comment by Plork** [comment]
any news on this since it's been a while ;)

**Comment by sandorfr** [comment]
> any news on this since it's been a while ;)

We did not have a big need around this for our extensions as the decision to mark a task as beta is still a manual action. So doing it in the task.json or another file is pretty much the same. 

Where it could be slightly more valuable would be in cases we want to decorelate the task version number from the extension. 

That where I am on it. If you have any thoughts or use cases to share let me know.

**Comment by Plork** [comment]
after playing around with it I see your point ;)

**Comment by sandorfr** [comment]
I'm closing this for now. Open to suggestions if the needs arises again.
