### ISSUE TITLE
Clear explanation of how to publish all types of build

### ISSUE THREAD

**Issue by marceloavf** [geeklearningio/gl-vsts-tasks-build-scripts#6]
I'm trying to understand how to publish this three types of release `dev`, `preview` and `production`.
They should be separated in VisualStudio `Manage Publishers & Extensions` or just be one extension?
![image](https://user-images.githubusercontent.com/5435657/35216799-0785333e-ff50-11e7-9d59-d3acdb365e7e.png)

For example, I have seen some extension that you can select `Preview` mode in the same task, e.g.
![image](https://user-images.githubusercontent.com/5435657/35216775-f061aaf2-ff4f-11e7-8dff-45a993a81ff0.png)

Thank you!

**Comment by sandorfr** [comment]
They are separate extensions. In our CD pipeline we publish the dev one continuously and we have our test builds in a repo based on that package. Once we are satisfied, we tag our release and we publishthe extension to the store as well. 

One thing from my experience we have never used the preview one so you could drop it (no one showed interest on getting early release). 

(PS, I'm very curious about your github extension as VSTS lacks a lot of thing in that area).

**Comment by marceloavf** [comment]
Nice, I will do something like that to keep dev always up-to-date for test purpose, here we use some dependencies to keep watching that changes.

I think the `preview` tag should help to test in a large scale, since you don't need to install another extension and pass all your settings just to test it.

For sure, we were planning on launch some releases and edit them by task, but all those extensions that already exists doesn't support some type of file, doesn't allow us to edit them (change from draft to pre-release to release) or simply doesn't work properly. I'm doing that by my self, very early stages since I don't understand everything very well, but you can see it here: [GitHub Tools](https://github.com/marceloavf/github-tools-vsts)

Thanks!

**Comment by sandorfr** [comment]
Yes major version bump with preview tag is a good way to push a beta to all
users without breaking their build as it does require them to make the
switch in their build definition.

However once you have a released one beta and some people have opted in you
may not want to push buggy stuff this is where the dev package is a good
approach.
