### ISSUE TITLE
Version extension

### ISSUE THREAD

**Issue by marceloavf** [geeklearningio/gl-vsts-tasks-build-scripts#8]
When creating my packages I see that it push a number next to the patch (999), why is that necessary ? Have seen that all others extensions don't use this approach, only the normal major.minor.patch.

**Comment by sandorfr** [comment]
We do that because we are using gitversion to automatically create the version number. We encode the semver metadata in the patch number. basically we use 1-998 for intermediate internal build.

**Comment by marceloavf** [comment]
I notice that in yours extensions, here we use [corp-semantic-release](https://github.com/leonardoanalista/corp-semantic-release) to keep watching all ours commits for `fix, feat and breaking changes`, so them it create a tag and email us for allow it to go to preview or release, we are planning on using also chat bots to make it easier. I also use GitVersion for feature/bugfix branches and pull request, it also watch our commits.

Is there a way to disable this number and use normally version?

Thank you again!

**Comment by sandorfr** [comment]
Yes there is : `npm run package -- --version "$Env:GitVersion_SemVer" --noversiontransform`
